---

- hosts: all
  become: true
  tasks:

  - name: install updates (Alma)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"
    
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php packages
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "AlmaLinux"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package (AlmaLinux)
    dnf:
      name: mariadb
      state: present
    when: ansible_distribution == "AlmaLinux"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      package:
        name: samba
        state: latest


