---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repository index (AlmaLinux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "AlmaLinux"
    
  - name: updates repository index (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: yes
  roles:
    - base

- hosts: workstations
  tags: mac,laptop
  become: true
  roles:
    - workstations

- hosts: web_servers
  tags: mac,laptop
  become: true
  roles:
    - web_servers

- hosts: db_servers
  tags: mac,laptop
  become: true
  roles:
    - db_servers

- hosts: file_servers
  tags: mac,laptop
  become: true
  roles:
    - file_servers