- name: install "{{ apache_package_name }}" and "{{ php_package_name }}"
  tags: apache,httpd,php
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start httpd (AlmaLinux)
  tags: httpd,php
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: copy default page
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

- name: change email address
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin redwan@example.net
  when: ansible_distribution == 'AlmaLinux'
  notify: restart_apache

