- name: install mariadb package (Ubuntu)
  apt:
    name: mariadb-server
    state: present
  when: ansible_distribution == "Ubuntu"
  
- name: install mariadb package (AlmaLinux)
  dnf:
    name: mariadb
    state: present
  when: ansible_distribution == "AlmaLinux"