- name: install unzip
  package:
    name: unzip
    state: present
    
- name: install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.0.9/terraform_1.0.9_darwin_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: redwan
    group: redwan